### ISSUE TITLE
Add a dropdown choice on the gui

### ISSUE THREAD

**Issue by lakruzz** [prolike/was-drop-gdpr#2]
Use the input data, as meta data when the file is stored

**Comment by lakruzz** [comment]
When you upload a file, it's stored as a binary, and a corresponding `.json` file

e.g.
![image](https://user-images.githubusercontent.com/155492/40548648-94fb2994-6035-11e8-958d-fcde729ab6df.png)

The input the user provides, shall be stored in the `.json`

```json
{"id":"ccf1e737ccb20b8156c893eb991d3b8b","name":"Rocketology-Avionics-Locations.jpg","size":250015,"filesize":"244.16 kB","type":"image/jpeg","lastModifiedDate":"2018-05-23T09:20:22.759Z","link":"http://localhost:5000/download/ccf1e737ccb20b8156c893eb991d3b8b/","path":"/opt/youtransfer/uploads/ccf1e737ccb20b8156c893eb991d3b8b.binary","jsonPath":"/opt/youtransfer/uploads/ccf1e737ccb20b8156c893eb991d3b8b.json","uploaded":1527067222771,"expires":1527672022771,"bundle":"e409aedf-66a0-4086-9dbc-1125e5d17519"}%                         ```

**Comment by lakruzz** [comment]
The size is a timebox (one day's work)

**Comment by LouBNielsen** [comment]
The content of the .json files that are stored in the upload folder has information such as
id, name, size, filesize etc.

I assume that this is were the information is set, but I haven't been able to change the variables...

![image](https://user-images.githubusercontent.com/17924001/40838970-c97b9fa8-65a0-11e8-82dc-b0fba3a1cee8.png)

**Comment by LouBNielsen** [comment]
I'm beginning to think that I'm working with some cache issues.. And the cache is the reason why I can't see any changes.. 

Before, I have tried to delete the background picture of the webpage but the background picture was still there...
Maybe it's the same problem here..

**Comment by LouBNielsen** [comment]
That was it... 
I'm now able to append content to the .json file AND change the background picture...

**Comment by prolike** [comment]
This issue was moved to prolike/drop-gdpr#1

**Comment by prolike** [comment]
This issue was moved to prolike/drop-gdpr#2
