### ISSUE TITLE
Setup an automated build on docker

### ISSUE THREAD

**Issue by prolike** [prolike/was-drop-gdpr#5]
This repos should rebuild the docker image automatically when a label is pushed.

- [x] Set it up on Docker
- [ ] Configure the regexp to build only version labels

**Comment by prolike** [comment]
@LouBNielsen can you write a short status to this one, I think you already did some of it, Please add a blue (size) label.

When you have, remove the green "Action - needs grooming" label

**Comment by LouBNielsen** [comment]
I have created a docker build on this repo.
I have pushed it to hub.docker.com on the Prolike account.
I have created a automated build - if I trigger that build, it says 'Success'.

![image](https://user-images.githubusercontent.com/17924001/40611095-47ed5608-6275-11e8-91d6-375fca178baa.png)

**Comment by LouBNielsen** [comment]
Up next: Need more information on "Configure the regexp to build only version labels"
